version: '3.8'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - docker/db/.env

  api:
    build:
      dockerfile: docker/api/Dockerfile
      context: .
    image: trax-api:1.0
    depends_on:
      - db
    env_file:
      - docker/api/.env
    ports:
      - '3000:3000'
